export const RECEIVED = 'RECIEVED';
export const ADD_TO_LIST = 'ADD_TO_LIST';
export const FILTER = 'FILTER';
export const EMPTY_ARRAY = 'EMPTY_ARRAY';
export const SET_MY_LIST = 'SET_MY_LIST';
export const NOTES = 'NOTES';
export const COMPLETE = 'COMPLETE';
export const CHANGE_GRADE = 'CHANGE_GRADE'
export const USER_RECEIVED = 'USER_RECEIVED'
export const HANDLE_DETAIL_MODAL = 'HANDLE_DETAIL_MODAL'
export const OPEN_LOGIN_MODAL ='OPEN_LOGIN_MODAL'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
